GET http://localhost:3000/acc

###

GET http://localhost:3000/acc/WMWOFFICIAL

###

POST http://localhost:3000/acc
Content-Type: application/json

{
    "username": "WMWOFFICIAL",
    "password": "#Egg21@vsianAI",
    "email": "thewmbexecutegang@gmail.com",
    "VIP": true,
    "created_date": 0,
    "updated_date": 0,
    "resources": [
        {
            "id": 1,
            "amount": 6
        }
    ]
}

###
GET http://localhost:8000/json

###

GET http://localhost:8000/json/resources

###

GET http://localhost:8000/json/resources/1